services:
  app:
    build: .
    container_name: adms-php
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8   # <-- Change from mysql:5.7 to mysql:8
    container_name: adms-db
    restart: unless-stopped
    platform: linux/amd64  # <-- Force amd64 compatibility if needed
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adms
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
